name: Deploy to GCP

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: nightzero
  REGION: us-central1
  SERVICE_NAME: demo-payment-gateway

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/164161200079/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions@nightzero.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet
          docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/nightzero/${SERVICE_NAME}:${GITHUB_SHA} .
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/nightzero/${SERVICE_NAME}:${GITHUB_SHA}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/nightzero/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Trigger Checkout to verify (and fire error if bug is present)
        run: |
          curl -X POST ${{ steps.deploy.outputs.url }}/checkout -H "Content-Type: application/json" -d '{"cents": 1234}'
